# This file contains all available configuration options
# with their default values (in comments).
#
# This file is not a configuration example,
# it contains the exhaustive configuration with explanations of the options.

version: "2"

linters:
  # Default set of linters.
  # The value can be: `standard`, `all`, `none`, or `fast`.
  # Default: standard
  default: all

  enable:
    - revive

  # All available settings of specific linters.
  settings:
    cyclop:
      # The maximal code complexity to report.
      # Default: 10
      max-complexity: 10
      # The maximal average package complexity.
      # If it's higher than 0.0 (float) the check is enabled
      # Default: 0.0
      package-average: 0.5
    tagliatelle:
      case:
        rules:
          json: snake
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck

run:
  # Timeout for total work, e.g. 30s, 5m, 5m30s.
  # If the value is lower or equal to 0, the timeout is disabled.
  # Default: 0 (disabled)
  timeout: 5m
